"""role permission

Revision ID: 92031cc2417a
Revises: 9befe60e0678
Create Date: 2018-08-23 22:10:52.171675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92031cc2417a'
down_revision = '9befe60e0678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
